# Generated by Django 5.2.17 on 2026-09-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_id', models.CharField(max_length=200, unique=True)),
                ('is_new', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(blank=True, max_length=60)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=60)),
                ('definition', models.TextField(blank=True)),
                ('extra_aliases', models.JSONField(blank=True, default=list)),
                ('def_location', models.CharField(blank=True, max_length=80)),
                ('man', models.CharField(blank=True, max_length=80)),
                ('origin', models.CharField(choices=[('editor', 'editor'), ('claude', 'generat de AI')], default='editor', max_length=20)),
                ('author', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('passage', models.TextField(blank=True)),
                ('selection', models.CharField(blank=True, max_length=200)),
                ('explanation', models.TextField(blank=True)),
                ('visibility', models.CharField(default='public', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelationEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'adăugare'), ('hide', 'ascundere')], max_length=10)),
                ('subj', models.CharField(max_length=200)),
                ('pred', models.CharField(max_length=40)),
                ('obj', models.CharField(max_length=200)),
                ('relation_id', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
